### ISSUE TITLE
More detailed explaination of settings

### ISSUE THREAD

**Issue by zhimsel** [rlidwka/sinopia-ldap#10]
Is there any way you could update the README with what each of the LDAP settings are? I'm having issues connecting sinopia to my LDAP directory. I keep getting "NoSuchObject", even though I know the object I'm specifying exists. I'm wondering if I'm maybe specifying an incorrect search scope or something. I'm not an LDAP expert :/

**Comment by rlidwka** [comment]
> Is there any way you could update the README with what each of the LDAP settings are?

When you figure it out, you're welcome to send a pull request explaining them. :)

Unfortunately, I don't know even less about LDAP than you do. This plugin is based on this pull request: https://github.com/rlidwka/sinopia/pull/99 , and I made it as an example of how to do a custom plugin. I wanted for people who know LDAP well to for it/take over its development, but nobody did.

So the only changes here are from random pull requests.

Maybe you could ask the same question here: https://github.com/vesse/node-ldapauth-fork .  That's the ldap driver this plugin uses, and all settings are mostly supplied there as is.

**Comment by zhimsel** [comment]
Ah, I understand. I'll definitely submit a PR if I do figure it out. Thanks for the links!
